### ISSUE TITLE
Bug : Not working with internal URL.

### ISSUE THREAD

**Issue by nervusdm** [kamranahmedse/pennywise#61] opened 2018-11-05 13:31 UTC
**Do you want to request a *feature* or report a *bug*?**
If I type in the URL : 
http://webtest2/example/

I cant reach the website. (even if it works perfectly on Chrome / ff /ie..

**What is the current behavior?**
Cant reach URL : 
Try a search on google. I cant copy & past in the navbar it doesnt work.

**Expected behavior**
Go on the internal website.

**Screenshots**

**Pennywise Version:**
0.5.1
**OS / OS Version:**
Windows 10.

**Comment by The-Code-Monkey** [comment] 2018-11-05 13:39
It does work because I use it for local testing when web developing. Must be something to do with your hosts file

**Comment by kamranahmedse** [comment] 2018-11-05 17:08
Thank you for reporting the issue. I am not able to reproduce this, so will have to close the issue.

**Closed by kamranahmedse** 2018-11-05 17:08 UTC

**Comment by nervusdm** [comment] 2018-11-05 18:17
Of course it works in the browser..

> Must be something to do with your hosts file

And ?
If I change the /etc/host.. what's the matter since it works in chrome, ff, ie not in pennywise ?

is this a bug tracker or a "ITS WORKS AS excepted" ?

**Comment by The-Code-Monkey** [comment] 2018-11-05 18:21
Well I have 5 sites currently in my hosts file and all 5 work through the penny-wise app so I can't see it being a ln app issue

**Comment by nervusdm** [comment] 2018-11-05 19:47
So if it works for you, it's not a bug ?
Well well well.

**Comment by The-Code-Monkey** [comment] 2018-11-05 20:00
If it works for 5 instances of mine there musnt be an issue send me your hosts file and ill see whats wrong.
